# Generated by Django 5.1.2 on 2024-11-21 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
